### PR TITLE
Fix determine filter adapter error when loading filter policy

### LINKED ISSUE #110: Determine filter adapter error when loading filter policy
It will still throw an exception when the adapter is `IFilteredAdapter`.

### PR DESCRIPTION
**Pull request by Sagilio**
close #110

### CODE REVIEW

**Comment by hsluoyz** [comment]
@xcaptain plz review.

File: NetCasbin/CoreEnforcer.cs [hunk 1]
```diff
@@ -213,11 +213,13 @@ public async Task LoadPolicyAsync()
         public bool LoadFilteredPolicy(Filter filter)
         {
             model.ClearPolicy();
-            if (!IsFiltered())
+            if (adapter is not IFilteredAdapter filteredAdapter)
```
Comment (xcaptain) [inline NetCasbin/CoreEnforcer.cs:216]: Don't understand why here would throw an exception if adapter is `IFilteredAdapter`.

```C#
!IsFiltered()
```

is the same as

```C#
adapter is not IFilteredAdapter filteredAdapter
```

**Review by xcaptain — APPROVED** [review]
Reply to my comments and then ready to merge.

File: NetCasbin/CoreEnforcer.cs (hunk 1 above)
Comment (Sagilio) [reply NetCasbin/CoreEnforcer.cs:216]: It will throw an exception when the adapter is not IFilteredAdapter. The result of `!IsFiltered()` will also return false when the adapter is `IFilteredAdapter` but `IsFiltered` is true.
