### PR TITLE
Change update policy workflow

### LINKED ISSUE #19: No rollback of memory data when adapter throw exception
In InternalEnforcer.cs, there are 3 methods add or remove policy data. All these methods will add or delete data in memory first then call adapter to perform the mutation of data in data store behind the adapter.

It will cause data inconsistency issue if no revert or rollback logic in all those methods. Please refers to the  bold area of the partial code below: 

```c#
bool ruleAdded = model.AddPolicy(sec, ptype, rule);
if (!ruleAdded)
{
    return false;
}

if (adapter != null && autoSave)
{
    try
    {
        await adapter.AddPolicyAsync(sec, ptype, rule);
    }
    catch (NotImplementedException)
    {
    }
    catch (Exception e)
    {
       **// rollback logic to revert the related memory data**
        throw e;
    }

    if (watcher != null)
    {
        // error intentionally ignored
        watcher.Update();
    }
}
```

### PR DESCRIPTION
**Pull request by Sagilio**
close #19

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Sagilio which is better for Boolean v.s. bool? and String v.s. string? Please use another PR to fix all styles, not this one.

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain @nodece please review.

**Comment by hsluoyz** [comment]
@Sagilio the AppVeyor seems to failed. Can you make a PR to fix that first? So we can have good-to-go CI in this PR: https://ci.appveyor.com/project/hsluoyz/casbin-net/builds/33452140

**Comment by Sagilio** [comment]
> @Sagilio the AppVeyor seems to failed. Can you make a PR to fix that first? So we can have good-to-go CI in this PR: https://ci.appveyor.com/project/hsluoyz/casbin-net/builds/33452140

I try to run this [build](https://ci.appveyor.com/project/Sagilio/casbin-net/builds/33452263) at my fork repository, It has not this error. So I think it may this ci option caused.

image

File: NetCasbin/InternalEnforcer.cs [hunk 1]
```diff
@@ -17,34 +17,26 @@ public class InternalEnforcer : CoreEnforcer
         /// <returns></returns>
         protected Boolean AddPolicy(String sec, String ptype, List<String> rule)
         {
-            Boolean ruleAdded = model.AddPolicy(sec, ptype, rule);
-            if (!ruleAdded)
-            {
-                return false;
-            } 
-
             if (adapter != null && autoSave)
```
Comment (nodece) [inline NetCasbin/InternalEnforcer.cs:20]: I suggest call model.HasPolicy to check if the policy can be added to adapter.

File: NetCasbin/InternalEnforcer.cs [hunk 2]
```diff
@@ -17,34 +17,26 @@ public class InternalEnforcer : CoreEnforcer
...
-                    watcher.Update();
                 }
             }
-            return true;
+
+            var ruleAdded = model.AddPolicy(sec, ptype, rule);
+
+            if (ruleAdded)
+            {
+                watcher?.Update();
```
Comment (nodece) [inline NetCasbin/InternalEnforcer.cs:36]: Move `watcher?.Update()` to  line 31

File: NetCasbin/InternalEnforcer.cs [hunk 3]
```diff
@@ -17,34 +17,26 @@ public class InternalEnforcer : CoreEnforcer
...
-                if (watcher != null)
+                catch (NotImplementedException)
                 {
                     // error intentionally ignored
-                    watcher.Update();
                 }
             }
-            return true;
+
+            var ruleAdded = model.AddPolicy(sec, ptype, rule);
```
Comment (xcaptain) [inline NetCasbin/InternalEnforcer.cs:32]: I think this way won't have any effects. If `adapter.AddPolicy` failed, the model will still be updated, I have 2 ideas about this.

1. Modify `AddPolicy` to return a bool rather than void
2. If `AddPolicy` throws an exception on fail, `model.AddPolicy` shouldn't be executed.

I personally prefer method1, because if an adapter fails, we can do nothing to recover it, so throw an exception doesn't help much. Of course method 2 is also ok, as long as we keep model and adapter be consistent.

File: NetCasbin/InternalEnforcer.cs (hunk 2 above)
Comment (Sagilio) [reply NetCasbin/InternalEnforcer.cs:36]: We should call `watcher?.Update()` before the memory changed include delete?

File: NetCasbin/InternalEnforcer.cs (hunk 1 above)
Comment (Sagilio) [reply NetCasbin/InternalEnforcer.cs:20]: You are right, I changed it.

**Comment by hsluoyz** [comment]
> I try to run this [build](https://ci.appveyor.com/project/Sagilio/casbin-net/builds/33452263) at my fork repository, It has not this error. So I think it may this ci option caused.

@Sagilio so how to fix it? What value should I change it to?

File: NetCasbin/InternalEnforcer.cs (hunk 3 above)
Comment (Sagilio) [reply NetCasbin/InternalEnforcer.cs:32]: I think also the method 1 better than method 2, but it may a breaking change to all adapter, If we use method 2 we can also catch all the exceptions to safely return. It like this:
```csharp
if (adapter != null && autoSave)
{
    try
    {
        adapter.AddPolicy(sec, ptype, rule);
    }
    catch (NotImplementedException)
    {
        // error intentionally ignored
    }
    catch
    {
        return false;
    }
}
```

Comment (xcaptain) [reply NetCasbin/InternalEnforcer.cs:32]: Agree with you, go ahead.

File: NetCasbin/InternalEnforcer.cs (hunk 2 above)
Comment (nodece) [reply NetCasbin/InternalEnforcer.cs:36]: yes.

Comment (nodece) [reply NetCasbin/InternalEnforcer.cs:36]: It's better to add `watcher?.Update()` to `try...finally` of adapter.

File: NetCasbin/InternalEnforcer.cs (hunk 3 above)
Comment (nodece) [reply NetCasbin/InternalEnforcer.cs:32]: throw exception is better here.

File: NetCasbin/InternalEnforcer.cs (hunk 2 above)
Comment (Sagilio) [reply NetCasbin/InternalEnforcer.cs:36]: Ok, I will add it to `finally` of adapter.

File: NetCasbin/InternalEnforcer.cs (hunk 3 above)
Comment (Sagilio) [reply NetCasbin/InternalEnforcer.cs:41]: > throw exception is better here.

I have thrown exception at here like before.

**Comment by hsluoyz** [comment]
@Sagilio please resolve conflicts.

File: NetCasbin/InternalEnforcer.cs [hunk 4]
```diff
@@ -17,34 +17,29 @@ public class InternalEnforcer : CoreEnforcer
...
-            var ruleAdded = model.AddPolicy(sec, ptype, rule);
-            if (!ruleAdded)
+            if (model.HasPolicy(sec, ptype, rule))
             {
-                return false;
-            } 
-
+                return true;
+            }
+
```
Comment (hsluoyz) [inline NetCasbin/InternalEnforcer.cs:24]: Remove spaces.

File: NetCasbin/InternalEnforcer.cs [hunk 5]
```diff
@@ -17,34 +17,29 @@ public class InternalEnforcer : CoreEnforcer
...
         protected bool AddPolicy(string sec, string ptype, List<string> rule)
         {
-            var ruleAdded = model.AddPolicy(sec, ptype, rule);
-            if (!ruleAdded)
+            if (model.HasPolicy(sec, ptype, rule))
             {
-                return false;
-            } 
-
+                return true;
```
Comment (hsluoyz) [inline NetCasbin/InternalEnforcer.cs:22]: See the docs: https://casbin.org/docs/en/management-api#addpolicy

`
If the rule already exists, the function returns false and the rule will not be added.
`

File: NetCasbin/InternalEnforcer.cs [hunk 6]
```diff
@@ -17,34 +17,29 @@ public class InternalEnforcer : CoreEnforcer
...
+                finally
                 {
-                    throw e;
-                }
-
-                if (watcher != null)
-                {
-                    // error intentionally ignored
-                    watcher.Update();
+                    watcher?.Update();
```
Comment (hsluoyz) [inline NetCasbin/InternalEnforcer.cs:37]: If `NotImplementedException` is caught, it means the adapter doesn't support Auto-Save, the adapter side will always fail. DB is also not updated. Why would we update the watcher?

**Comment by hsluoyz** [comment]
We should also clarify one thing: if an adapter doesn't support Auto-Save, then calling enforcer's add/remove policy will only modify the local model, since DB side will never be updated.

File: NetCasbin/InternalEnforcer.cs (hunk 4 above)
Comment (Sagilio) [reply NetCasbin/InternalEnforcer.cs:24]: I think these spaces are necessary, the method body look like this:
```csharp
protected bool AddPolicy(string sec, string ptype, List<string> rule)
{
    if (model.HasPolicy(sec, ptype, rule))
    {
        return false;
    }

    if (adapter != null && autoSave)
    {
        try
        {
            adapter.AddPolicy(sec, ptype, rule);
        }
        catch (NotImplementedException)
        {
            // error intentionally ignored
        }

        watcher?.Update();
    }

    var ruleAdded = model.AddPolicy(sec, ptype, rule);
    return ruleAdded;
}
```

Comment (hsluoyz) [reply NetCasbin/InternalEnforcer.cs:24]: By spaces I mean the " " (space chars) in the empty line:

image

Comment (Sagilio) [reply NetCasbin/InternalEnforcer.cs]: Ok, I removed the spaces.

File: NetCasbin/InternalEnforcer.cs [hunk 7]
```diff
@@ -17,34 +17,27 @@ public class InternalEnforcer : CoreEnforcer
...
-                }
-
-                if (watcher != null)
+                catch (NotImplementedException)
                 {
                     // error intentionally ignored
-                    watcher.Update();
                 }
+
+                watcher?.Update();
```
Comment (nodece) [inline NetCasbin/InternalEnforcer.cs:36]: If the adapter does not update the policy,  it is unnecessary to call the watcher.

**Comment by hsluoyz** [comment]
Approved.

What do you think? @xcaptain @nodece

**Comment by nodece** [comment]
LGTM

**Comment by hsluoyz** [comment]
@huazhikui please release a new version
